# ==============================================================================
# DEVFORGE COMPOSE GENERATION ENGINE
# ==============================================================================
# Reads plugin compose.fragment.yaml files, merges them into a complete,
# valid docker-compose.yml for a specific project.
# Generates profile-specific variants (dev, testing, production).
# ==============================================================================

from __future__ import annotations

from pathlib import Path
from typing import Optional

import yaml
from jinja2 import Environment, FileSystemLoader, StrictUndefined
from rich.console import Console

from engine.workspace import Project, get_devforge_root

console = Console()

WORKSPACE_ROOT = Path("/workspace")
PLUGINS_DIR = get_devforge_root() / "plugins"

# Shared YAML anchors injected at the top of every generated compose file
COMPOSE_PREAMBLE = """\
# ==============================================================================
# GENERATED BY DEVFORGE v2
# Project: {{ project_name }}
# Profile: {{ profile }}
# Generated: {{ generated_at }}
# DO NOT EDIT MANUALLY — regenerate with: devforge plugin install <name>
# ==============================================================================

"""

DEFAULT_LOGGING = {
    "driver": "json-file",
    "options": {
        "max-size": "10m",
        "max-file": "3"
    }
}

SECURITY_DEFAULTS = {
    "security_opt": [
        "no-new-privileges:true"
    ],
    "cap_drop": [
        "ALL"
    ]
}


class CustomAnchorDumper(yaml.SafeDumper):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.custom_anchors = {}

    def represent_data(self, data):
        node = super().represent_data(data)
        if data == DEFAULT_LOGGING:
            self.custom_anchors[id(node)] = "default-logging"
        elif data == SECURITY_DEFAULTS:
            self.custom_anchors[id(node)] = "security-defaults"
        return node

    def generate_anchor(self, node):
        if id(node) in self.custom_anchors:
            return self.custom_anchors[id(node)]
        return super().generate_anchor(node)


# Profile-specific environment overrides applied on top of fragments
PROFILE_ENV_OVERRIDES = {
    "dev": {
        "NODE_ENV": "development",
        "DJANGO_DEBUG": "true",
        "LOG_LEVEL": "debug",
    },
    "testing": {
        "NODE_ENV": "test",
        "DJANGO_DEBUG": "false",
        "LOG_LEVEL": "info",
    },
    "production": {
        "NODE_ENV": "production",
        "DJANGO_DEBUG": "false",
        "LOG_LEVEL": "warning",
        "RESTART_POLICY": "always",
    },
}


class ComposeGenerator:
    """Merges plugin compose fragments into a complete docker-compose.yml."""

    def __init__(self):
        self._jinja_env = Environment(
            loader=FileSystemLoader(str(WORKSPACE_ROOT)),
            undefined=StrictUndefined,
            keep_trailing_newline=True,
        )

    def generate(
        self,
        project: Project,
        plugins: list[str],
        plugin_versions: dict[str, str],
        frameworks: dict,
        ports: dict,
        profile: str = "dev",
    ) -> str:
        """
        Generate a docker-compose.yml string for the given plugin list and profile.
        Returns the rendered YAML string.
        """
        from datetime import datetime, timezone

        context = {
            "project_name": project.name,
            "profile": profile,
            "generated_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
            "ports": ports,
            **frameworks,
        }

        # Collect all services, volumes, and networks from plugin fragments
        all_services: dict = {}
        all_volumes: set = set()

        for plugin_name in plugins:
            fragment_path = self._resolve_fragment(plugin_name, plugin_versions.get(plugin_name))
            if not fragment_path:
                console.print(
                    f"[yellow]  ⚠ Plugin '{plugin_name}' has no compose fragment — skipping.[/yellow]"
                )
                continue

            rendered = self._render_fragment(fragment_path, context)
            # Prepend minimal anchors preamble to resolve aliases during safe loading
            anchors_preamble = """\
x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

x-security-defaults: &security-defaults
  security_opt:
    - no-new-privileges:true
  cap_drop:
    - ALL
"""
            fragment_data = yaml.safe_load(anchors_preamble + "\n" + rendered)

            if not fragment_data:
                continue

            services = fragment_data.get("services", {})
            volumes = fragment_data.get("volumes", {})

            # Apply profile-specific env overrides to each service
            profile_env = PROFILE_ENV_OVERRIDES.get(profile, {})
            for svc_name, svc_cfg in services.items():
                if profile_env and isinstance(svc_cfg, dict):
                    existing_env = svc_cfg.get("environment", {})
                    if isinstance(existing_env, list):
                        # Convert list env to dict, apply overrides
                        env_dict = {}
                        for item in existing_env:
                            if "=" in item:
                                k, v = item.split("=", 1)
                                env_dict[k] = v
                            else:
                                env_dict[item] = None
                        env_dict.update(profile_env)
                        svc_cfg["environment"] = env_dict
                    elif isinstance(existing_env, dict):
                        existing_env.update(profile_env)

                # Production: force restart: always
                if profile == "production":
                    svc_cfg["restart"] = "always"

            all_services.update(services)
            all_volumes.update(volumes.keys() if volumes else [])

        # Ensure identical object references are used for logging in services
        for svc_name, svc_cfg in all_services.items():
            if isinstance(svc_cfg, dict):
                if svc_cfg.get("logging") == DEFAULT_LOGGING:
                    svc_cfg["logging"] = DEFAULT_LOGGING

        # Build the final compose structure, putting anchors first to ensure they are visited first by PyYAML
        compose_dict = {
            "x-logging": DEFAULT_LOGGING,
            "x-security-defaults": SECURITY_DEFAULTS,
            "services": all_services,
            "networks": {
                "devforge-network": {
                    "name": f"devforge-{project.name}-network",
                    "driver": "bridge",
                }
            },
        }

        if all_volumes:
            compose_dict["volumes"] = {vol: None for vol in sorted(all_volumes)}

        # Render the preamble
        preamble_tmpl = self._jinja_env.from_string(COMPOSE_PREAMBLE)
        preamble = preamble_tmpl.render(**context)

        # Dump YAML using CustomAnchorDumper (suppress None values in volumes)
        yaml_body = yaml.dump(
            compose_dict,
            Dumper=CustomAnchorDumper,
            default_flow_style=False,
            sort_keys=False,
            allow_unicode=True,
        )

        return preamble + yaml_body

    def _resolve_fragment(
        self, plugin_name: str, version: Optional[str]
    ) -> Optional[Path]:
        """Locate the compose fragment for a plugin, respecting versions."""
        # Try versioned path first: plugins/postgres@16/compose.fragment.yaml
        if version:
            versioned = PLUGINS_DIR / f"{plugin_name}@{version}" / "compose.fragment.yaml"
            if versioned.exists():
                return versioned

        # Fall back to default: plugins/postgres/compose.fragment.yaml
        default = PLUGINS_DIR / plugin_name / "compose.fragment.yaml"
        return default if default.exists() else None

    def _render_fragment(self, fragment_path: Path, context: dict) -> str:
        """Render a Jinja2 compose fragment with the project context."""
        # Use a fresh loader scoped to the fragment's directory
        env = Environment(
            loader=FileSystemLoader(str(fragment_path.parent)),
            undefined=StrictUndefined,
            keep_trailing_newline=True,
        )
        # Ignore undefined variables gracefully in fragments
        env.undefined = type(
            "Undefined",
            (object,),
            {"__str__": lambda s: "", "__repr__": lambda s: ""},
        )
        try:
            tmpl = env.get_template(fragment_path.name)
            return tmpl.render(**context)
        except Exception:
            # If Jinja2 fails, return raw content as fallback
            return fragment_path.read_text()

    def write_compose_files(
        self,
        project: Project,
        plugins: list[str],
        plugin_versions: dict[str, str],
        frameworks: dict,
        ports: dict,
        skip_dev: bool = False,
    ):
        """
        Write docker-compose.yml (default dev) and all profile variants
        into the project directory.
        """
        project.ensure_devforge_dir()

        # Copy custom docker build context folders for the active plugins if they exist in DevForge
        import shutil
        devforge_root = get_devforge_root()
        for plugin in plugins:
            # Strip version suffix (e.g. postgres@16 -> postgres)
            base_plugin = plugin.split("@")[0].strip()
            src_docker_dir = devforge_root / "docker" / base_plugin
            if src_docker_dir.exists():
                dest_docker_dir = project.path / "docker" / base_plugin
                if not dest_docker_dir.exists():
                    try:
                        dest_docker_dir.parent.mkdir(parents=True, exist_ok=True)
                        shutil.copytree(src_docker_dir, dest_docker_dir)
                        console.print(f"  [green]✓[/green] Copied docker context for [bold]{base_plugin}[/bold]")
                    except Exception as e:
                        console.print(f"  [yellow]⚠ Failed to copy docker context for {base_plugin}: {e}[/yellow]")

        profiles = ["dev", "testing", "production"]

        for profile in profiles:
            if profile == "dev" and skip_dev:
                continue

            content = self.generate(
                project, plugins, plugin_versions, frameworks, ports, profile
            )

            if profile == "dev":
                # Default compose at project root
                target = project.compose_file
            else:
                # Profile variants in .devforge/generated/
                target = project.compose_for_profile(profile)

            target.write_text(content, encoding="utf-8")
            try:
                display_path = target.relative_to(Path('/workspace'))
            except ValueError:
                display_path = target
            console.print(
                f"  [green]✓[/green] Generated [bold]{display_path}[/bold]"
            )
